### ISSUE TITLE
If object defines a to_transit, it probably doesn't need to go through the transit writer again.

### ISSUE THREAD

**Issue by phillc** [jgdavey/transit-rails#3]
Hello,

In a console with rails,

`{}.to_json.class => String`
and
`{}.to_xml.class => String`

In both the json case, and the xml case, the to_format methods return a string with the object already in its final representation. I feel as though the expectation should be the same of `to_transit`.

Currently, I have a `to_transit` defined on hash, and it returns a string already passed through a transit writer. I had to do this because when the devise gem goes to return a 401 unauthorized when a user accesses a page that requires being logged in, [devise checks to see if `to_#{format}` exists on a hash](https://github.com/plataformatec/devise/blob/2ccffc80b020cb3ac21b5b1ecbdfc9cba9e0804b/lib/devise/failure_app.rb#L171-L181) and if it does, [devise returns that as the body of the response](https://github.com/plataformatec/devise/blob/2ccffc80b020cb3ac21b5b1ecbdfc9cba9e0804b/lib/devise/failure_app.rb#L50). If the method doesn't exist, devise responds with just a string with an error message. That is causing my app to explode, because that is not valid transit. I feel as though devise's expectation of the `to_#{format}` method is correct.

Perhaps the [current check for to_transit](https://github.com/jgdavey/transit-rails/blob/1d820b2deeb81ae1be3885f17e1cd911bb86e7f2/lib/transit/rails/renderer.rb#L38-L39) should actually be `as_transit`, and somewhere a check for `to_transit` can be made, and called perhaps with handlers passed in, with the value being used instead of sending it through the transit writer again.

Thanks

**Comment by jgdavey** [comment]
I think I agree. `as_transit` would be better here. Luckily, I don't think I ever documented the `to_transit` behavior, so the switch shouldn't hurt casual users (fingers crossed).

I plan to work on this soon.

**Comment by phillc** [comment]
My attempt was in pull request #4 . Let me know if I can provide any assistance .
